# Generated by Django 5.1.3 on 2024-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo_pdf', models.FileField(upload_to='editais/', verbose_name='Arquivo PDF')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
