# Generated by Django 5.1.3 on 2024-12-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_edital_arquivo_pdf_remove_edital_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='editais/'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='data_publicacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='edital',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
