# Generated by Django 5.1.3 on 2024-12-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_edital_arquivo_pdf_alter_edital_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], max_length=50),
        ),
    ]
