# Generated by Django 5.1.3 on 2024-12-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_edital_descricao_alter_edital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='arquivo_pdf',
            field=models.FileField(blank=True, default='path/to/default/file.pdf', null=True, upload_to='editais/'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edital',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=7),
        ),
        migrations.AlterField(
            model_name='edital',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
