# Generated by Django 5.0 on 2024-12-17 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_edital_arquivo_pdf_alter_edital_descricao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='editais/'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], max_length=50),
        ),
        migrations.CreateModel(
            name='HistoricoEditais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.edital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_editais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
