# Generated by Django 5.0 on 2024-12-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_perfil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
